language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "4.1"
sudo: false
script:
  - "npm test"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
